AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for storing aid request images in the Disaster Relief Coordinating Platform

Resources:
  AidRequestsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: disaster-aid-images-2025
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - "*"  # For development only; replace before production
              # - "https://your-frontend-domain.com"  # Example: Replace for production
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldImages
            Status: Enabled
            Prefix: aid-requests/
            ExpirationInDays: 90
            NoncurrentVersionExpirationInDays: 30

Outputs:
  AidRequestsBucketName:
    Description: "S3 Bucket used to store uploaded images for aid requests"
    Value: !Ref AidRequestsBucket
