AWSTemplateFormatVersion: '2010-09-09'
Description: Full stack for Disaster Relief Coordinating Platform (Lambda + API Gateway + DynamoDB + S3 + SNS)

Resources:

  AidRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AidRequests
      AttributeDefinitions:
        - AttributeName: request_id
          AttributeType: S
        - AttributeName: request_type
          AttributeType: S
      KeySchema:
        - AttributeName: request_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: RequestTypeIndex
          KeySchema:
            - AttributeName: request_type
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DisasterLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:Scan
                  - dynamodb:DeleteItem
                Resource: !GetAtt AidRequestsTable.Arn
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::disaster-aid-images-2025
                  - !Sub arn:aws:s3:::disaster-aid-images-2025/*
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:disaster-aid-alerts
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  UnifiedAidRequestFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: DisasterAidHandler
      Handler: lambda_handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.11
      Code:
        S3Bucket: disaster-aid-images-2025
        S3Key: disaster_relief_bundle.zip
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          BUCKET_NAME: disaster-aid-images-2025
          SNS_TOPIC_ARN: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:disaster-aid-alerts

  DisasterApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: DisasterReliefApi
      Description: "API for Disaster Relief Coordinating Platform"

  AidResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref DisasterApi
      ParentId: !GetAtt DisasterApi.RootResourceId
      PathPart: aid

  AidPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref AidResource
      RestApiId: !Ref DisasterApi
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - LambdaArn: !GetAtt UnifiedAidRequestFunction.Arn

  AidGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !Ref AidResource
      RestApiId: !Ref DisasterApi
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - LambdaArn: !GetAtt UnifiedAidRequestFunction.Arn

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - AidPostMethod
      - AidGetMethod
    Properties:
      RestApiId: !Ref DisasterApi
      StageName: dev

  UnifiedLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref UnifiedAidRequestFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DisasterApi}/*/*/aid

Outputs:
  LambdaFunctionName:
    Description: "Unified Lambda function for handling aid requests"
    Value: !Ref UnifiedAidRequestFunction

  ApiGatewayUrl:
    Description: "Base URL for API Gateway"
    Value: !Sub https://${DisasterApi}.execute-api.${AWS::Region}.amazonaws.com/dev/aid

  AidRequestsTableName:
    Description: "DynamoDB table for aid requests"
    Value: !Ref AidRequestsTable
