AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway for UnitedRelief Platform

Resources:

  UnitedReliefApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: UnitedReliefAPI
      Description: API for volunteer and aid form submissions

  VolunteerResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref UnitedReliefApi
      ParentId: !GetAtt UnitedReliefApi.RootResourceId
      PathPart: volunteer

  ReliefResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref UnitedReliefApi
      ParentId: !GetAtt UnitedReliefApi.RootResourceId
      PathPart: relief-request

  VolunteerPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref UnitedReliefApi
      ResourceId: !Ref VolunteerResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:SubmitVolunteerForm/invocations

  ReliefPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref UnitedReliefApi
      ResourceId: !Ref ReliefResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:SubmitReliefRequest/invocations

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - VolunteerPostMethod
      - ReliefPostMethod
    Properties:
      RestApiId: !Ref UnitedReliefApi
      StageName: dev

  VolunteerLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: SubmitVolunteerForm
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${UnitedReliefApi}/*/POST/volunteer

  ReliefLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: SubmitReliefRequest
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${UnitedReliefApi}/*/POST/relief-request

Outputs:
  ApiBaseUrl:
    Description: Base URL of the API Gateway
    Value: !Sub https://${UnitedReliefApi}.execute-api.${AWS::Region}.amazonaws.com/dev
