AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB Tables for UnitedRelief Platform

Resources:

  # === DynamoDB Table: VolunteerSubmissions ===
  VolunteerSubmissionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VolunteerSubmissions
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: submittedAt
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: submittedAt
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: UnitedRelief
        - Key: Environment
          Value: Development

  # === DynamoDB Table: ReliefRequests ===
  ReliefRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ReliefRequests
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: submittedAt
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: submittedAt
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: UnitedRelief
        - Key: Environment
          Value: Development

Outputs:

  VolunteerSubmissionsTableName:
    Description: Name of the DynamoDB table for volunteer submissions
    Value: !Ref VolunteerSubmissionsTable

  ReliefRequestsTableName:
    Description: Name of the DynamoDB table for relief requests
    Value: !Ref ReliefRequestsTable
