AWSTemplateFormatVersion: '2010-09-09'
Description: IAM role with scoped permissions for UnitedRelief Lambda functions

# === Resources ===
Resources:

  # === IAM Role: Lambda Execution ===
  UnitedReliefLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: UnitedReliefLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

      Policies:
        - PolicyName: UnitedReliefLambdaScopedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:

              # === DynamoDB Access ===
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Scan
                Resource:
                  - arn:aws:dynamodb:*:*:table/ReliefRequests
                  - arn:aws:dynamodb:*:*:table/VolunteerSubmissions

              # === S3 Access: ReliefRequests ===
              # Allows image uploads and read access for relief requests
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::unitedrelief-submissions
                  - arn:aws:s3:::unitedrelief-submissions/*

              # === S3 Access: VolunteerSubmissions ===
              # Allows JSON backups and read access for volunteer submissions
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::unitedrelief-volunteer-files
                  - arn:aws:s3:::unitedrelief-volunteer-files/*

              # === CloudWatch Logs Access ===
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

              # === Secrets Manager Access ===
              # Used to retrieve Gmail SMTP credentials securely
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - arn:aws:secretsmanager:*:*:secret:unitedrelief/gmail-*

# === Outputs ===
Outputs:
  LambdaExecutionRoleArn:
    Description: ARN of the UnitedRelief Lambda execution role
    Value: !GetAtt UnitedReliefLambdaExecutionRole.Arn
    Export:
      Name: LambdaExecutionRoleArn
