AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Functions for UnitedRelief Platform

Parameters:
  CodeBucket:
    Type: String
    Description: Name of the S3 bucket containing Lambda ZIP files

Resources:

  # === Lambda Function: SubmitReliefRequest ===
  SubmitReliefRequestFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SubmitReliefRequest
      Description: Handles disaster relief request form submissions
      Runtime: python3.11
      Role: !ImportValue LambdaExecutionRoleArn
      Handler: relief_request.lambda_handler
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: relief_request.zip
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          GMAIL_SECRET_NAME: unitedrelief/gmail
          S3_BUCKET: unitedrelief-submissions
          DYNAMODB_TABLE: ReliefRequests
          SNS_TOPIC_ARN: arn:aws:sns:us-east-1:650856831762:unitedrelief-submissions-alerts
      Tags:
        - Key: Project
          Value: UnitedRelief
        - Key: Environment
          Value: Dev

  # === Lambda Function: SubmitVolunteerForm ===
  SubmitVolunteerFormFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SubmitVolunteerForm
      Description: Handles volunteer form submissions
      Runtime: python3.11
      Role: !ImportValue LambdaExecutionRoleArn
      Handler: volunteer_form.lambda_handler
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: volunteer_form.zip
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          GMAIL_SECRET_NAME: unitedrelief/gmail
          S3_BUCKET: unitedrelief-submissions
          DYNAMODB_TABLE: VolunteerSubmissions
          SNS_TOPIC_ARN: arn:aws:sns:us-east-1:650856831762:unitedrelief-submissions-alerts
      Tags:
        - Key: Project
          Value: UnitedRelief
        - Key: Environment
          Value: Dev

Outputs:
  ReliefFunctionName:
    Description: Name of the SubmitReliefRequest Lambda function
    Value: !Ref SubmitReliefRequestFunction

  VolunteerFunctionName:
    Description: Name of the SubmitVolunteerForm Lambda function
    Value: !Ref SubmitVolunteerFormFunction
