AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for UnitedRelief image and data submissions

Resources:

  UnitedReliefSubmissionsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: unitedrelief-submissions

      AccessControl: Private
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - "https://unitedrelief.vercel.app"
            MaxAge: 3000

      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldReliefImages
            Status: Enabled
            Prefix: relief-images/
            ExpirationInDays: 90

Outputs:
  UnitedReliefBucketName:
    Description: S3 bucket for storing relief request image uploads
    Value: !Ref UnitedReliefSubmissionsBucket
